
import { AreaChartOutlined, AuditOutlined, BankOutlined, CalendarOutlined, CheckCircleOutlined, CodepenOutlined, DeleteOutlined, EditOutlined, PlusCircleOutlined, PlusOutlined, SearchOutlined, SnippetsOutlined, StopOutlined, UserOutlined, UsergroupDeleteOutlined, WarningOutlined } from "@ant-design/icons";
import { Button, Form, Input, InputNumber, Modal, Popconfirm, Select, Table, Tag } from "antd";
import Cookies from "js-cookie";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Layout from "../layouts";
import { ToastContainer, toast } from 'react-toastify';
import moment from "moment/moment";

import { DatePicker, Space } from 'antd';
import Link from "next/link";
const { RangePicker } = DatePicker;



export default function Home() {
    const router = useRouter();
    const [isModalOpen, setIsModalOpen] = useState(false);


    const showModal = () => {
        setIsModalOpen(true);
    };
    const handleOk = () => {
        setIsModalOpen(false);
    };
    const handleCancel = () => {
        setIsModalOpen(false);
    };


    const [from, setFrom] = useState(null);
    const [to, setTo] = useState(null);

    function onCalendarChange(dates, dateStrings) {
        setFrom(dateStrings[0])
        setTo(dateStrings[1])
    }



    return (


        <Layout>
            <Head>
                <title>EEDO</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div>


                <div className="p-2  mt-2 bg-white shadow-md rounded">
                    <div className="font-poppins font-inter   lg:grid lg:grid-cols-4 xl:gap-x-2  gap-y-2 gap-x-2 hover:cursor-pointer"
                        // onClick={() => {
                        //     router.push({
                        //         pathname: '/reports/supervisor',
                        //         query: {
                        //             drawTime: 17
                        //         },
                        //     }, `reports/supervisor`, {})

                        // }}

                        // onClick={showModal}

                    >

                        {/* <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500'
                         onClick={() => {
                            router.push({
                                pathname: '/reports/supervisorGross',
                                // query: {
                                //     drawTime: 17
                                // },
                            }, `reports/supervisorGross`, {})

                        }}>
                            <div className=''>
                                <UserOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                     Gross per Supervisors
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                        </div>
                       
                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                         onClick={() => {
                            router.push({
                                pathname: '/reports/tellerGross',
                                // query: {
                                //     drawTime: 17
                                // },
                            }, `reports/tellerGross`, {})

                        }}>
                            <div className=''>
                                <UsergroupDeleteOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                Gross per Tellers
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div> */}


                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/tellerVoids',
                                // query: {
                                //     drawTime: 17
                                // },
                            }, `reports/tellerVoids`, {})

                        }}
                        >
                            <div className=''>
                                <StopOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                Void per Tellers
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>


                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/activeTellers',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <CheckCircleOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                               Active Tellers
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>


                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/tellerTransactions',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <SnippetsOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                Teller Transactions
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>

                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/tellerAttendance',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <CalendarOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                Tellers Attendance
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>


                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/tellerReports',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <CalendarOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                Tellers Reports
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>





                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/GrossDaterange',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <CalendarOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                                General Daily Gross 
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>




                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/GrossPerMunicipality',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <BankOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                               Gross Per Municipality
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>




                        
                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/WeeklyGross',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <AreaChartOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                              Weekly Salary
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>

                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/Claimed',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <AuditOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                              Claimed Winning Tickets
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>


                        <div className='hover:bg-slate-200  grid grid-cols-3 border border-solid p-2 mt-1  rounded shadow-lg bg-white  border-slate-500' 
                          onClick={() => {
                            router.push({
                                pathname: '/reports/Unclaimed',
                                // query: {
                                //     drawTime: 17
                                // },
                            })

                        }}
                        >
                            <div className=''>
                                <WarningOutlined
                                    className='text-slate-500'
                                    style={{ fontSize: 50 }}
                                />
                            </div>

                            <div className='col-span-2'>
                                <span className='block font-semibold text-slate-500'>
                              Unclaimed Winning Tickets
                                </span>
                                <span className='text-xs text-slate-500'>Management</span>
                            </div>
                            
                        </div>

                        
                    </div>

                </div>
            </div>



            <Modal title="Select Date" open={isModalOpen} onOk={handleOk} onCancel={handleCancel}

                okButtonProps={{ style: { display: 'none' } }}
                cancelButtonProps={{ style: { display: 'none' } }}
            >
                <div>
                    <Space direction="vertical" size={12}>
                        <RangePicker onCalendarChange={onCalendarChange} />

                        <Link
                            href={{
                                pathname: '/reports/supervisor/pdf',
                                query: {
                                    from: from,
                                    to: to
                                },
                            }}

                            target="_blank"
                        >

                            <Button type="primary">Generate</Button>

                        </Link>

                        {/* <Button type="primary" onClick={() => {
                            router.push({
                                pathname: '/reports/supervisor/pdf',
                                query: {
                                    drawTime: 17
                                },
                            }, `supervisor/pdf`, {})

                        }}>Generate</Button> */}
                    </Space>
                </div>
            </Modal>

        </Layout>
    )




}


